version: '3'

services:

  nginx:
    image: nginx:latest
    container_name: proxy
    volumes:
    - ${PWD}/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
    - 80:80
    - 443:443
    links:
    - keycloak
  keycloakdb:
      image: postgres:13.1
      container_name: postgres_keycloak
      volumes:
        - ${PWD}/target/keycloak-data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: secret
  te2mdb:
    image: mariadb
    container_name: mariadb_te2m
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: te2m
      MYSQL_USER: te2m
      MYSQL_PASSWORD: secret
    restart: on-failure
    volumes:
      - ${PWD}/target/te2m-data:/var/lib/mysql
  keycloak:
      image: jboss/keycloak:11.0.3
      volumes:
        - ${PWD}/keycloak/te2m-realm.json:/opt/jboss/keycloak/te2m-realm.json
      # ok for now in order to import test data, should not be used in prod
      command: -Dkeycloak.profile.feature.upload_scripts=enabled
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: keycloakdb
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: secret
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
        #KEYCLOAK_IMPORT_REALM: ./te2m-realm.json
        KEYCLOAK_IMPORT: /opt/jboss/keycloak/te2m-realm.json
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
      ports:
       - 8080:8080
      depends_on:
        - keycloakdb
